### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by raoul-thill** [anvilco/spectaql#16]
Thanks for this great utility to generate nice-looking GraphQL documentations! One feature I am missing or don't know exactly how to start with as it could probably be done with the customizations is filtering.

Is it possible to filter some defined queries, mutations and types from the generated documentation?

**Comment by raoul-thill** [comment]
I figured out how to do filtering, if someone is struggling with the same, you have to look into metadata and the introspection parameters to show or hide queries, mutations and types.
If you show everything (default) you would have something like this in your metadata.json:
```json
{
  "OBJECT": {
    "UserType": {
      "documentation": { "undocumented": true }
    },
    "Query": {
      "fields": {
        "Users": {
          "documentation": { "undocumented": true }
        }
      }
    }
  }
}
```

In case you only want to do whitelisting, you should configure in you config.yaml:
```yaml
introspection:
  url: http://localhost:8000/graphql/
  metadataFile: ./metadata.json

  queryDocumentedDefault: false
  mutationDocumentedDefault: false
  typeDocumentedDefault: false
```

together with a metadata.json:
```json
{
  "OBJECT": {
    "UserType": {
      "documentation": { "documented": true }
    },
    "Query": {
      "fields": {
        "Users": {
          "documentation": { "documented": true }
        }
      }
    }
  }
}
```

This makes it a perfect utility to generate very nice-looking documentation for internal use only and public distribution.

**Comment by newhouse** [comment]
@raoul-thill Nice work!

This is correct: if your config says to allow every `Query`/`Mutation`/`Type` by default, then you will have to use documentation-related metadata to indicate which things you'd like to blacklist...and vice versa.

Your 2 main options for getting that metadata into the mix for `SpectaQL` to obey are:
1. Put it in a separate JSON file in the proper format, and point to that JSON file with the `metadataFile` key/value in your config YAML (This is what the above example has done)
OR
2. Get it pre-woven into your Introspection Query results. How to do that is very stack-specific, but we have published an [Apollo plugin](https://www.npmjs.com/package/@anvilco/apollo-server-plugin-introspection-metadata) (and discussed the approach in our [blog post](https://www.useanvil.com/blog/2021-03-17-autogenerate-graphql-docs-with-spectaql)) if you happen to be using the same stack as us.

Thanks agin for using SpectaQL!

**Comment by raoul-thill** [comment]
@newhouse, after having a more in-depth look at the public/restricted documentation, I can see that fields and args are missing on objects for example. The same for mutations and queries where I don't have the example args.

From my initial example, how can I have a metadata.json file that works for the OBJECT UserType to include all the fields and to have all args displayed in the generated documentation? Do I have to specify each of them in the metadata.json?

**Comment by newhouse** [comment]
@raoul-thill

Can you provide a simple `schema` and `config` that I can run to reproduce what you're talking about? A screenshot of the incorrect part of the output would help, too. That would make it much easier for me make sure we're on the same page, and for me to fix it for you.

**Comment by raoul-thill** [comment]
@newhouse 

Sure, please find the files below:

schema.sdl:
```graphql
"""Generate JWT for user"""
type AuthenticateUser {
  bearerToken: String
  expiresIn: Int
}

type Mutation {
  """Generate JWT for user"""
  authenticateUser(
    """Password"""
    password: String!

    """Username"""
    username: String!
  ): AuthenticateUser
}

type Query {
  """Get the health status of the system."""
  status: Status
}

"""Example health status."""
type Status {
  databaseEngine: String
  storageEngine: String
}
```

config-private.yml:
```yaml
introspection:
  schemaFile: ./doc/schema.sdl

servers:
  - url: http://localhost:8000/graphql/
    description: Dev
    production: true
```

config-public.yml:
```yaml
introspection:
  schemaFile: ./doc/schema.sdl
  metadataFile: ./doc/metadata.json

  queryDocumentedDefault: false
  mutationDocumentedDefault: false
  typeDocumentedDefault: false

servers:
  - url: http://localhost:8000/graphql/
    description: Dev
    production: false
```

metadata.json:
```json
{
  "OBJECT": {
    "AuthenticateUser": {
      "documentation": {
        "documented": true
      }
    },
    "Status": {
      "documentation": {
        "documented": true
      }
    },
    "Query": {
      "fields": {
        "status": {
          "documentation": {
            "documented": true
          }
        }
      }
    },
    "Mutation": {
      "fields": {
        "authenticateUser": {
          "documentation": {
            "documented": true
          }
        }
      }
    }
  }
}
```

The result can be seen below, on the left side is the public using metadata.json and on the right side the private version without any special configuration:
![image](https://user-images.githubusercontent.com/70886316/117123895-e8109580-ad97-11eb-8e79-f7cd0eb951e5.png)

**Comment by raoul-thill** [comment]
I have slightly adapted my configuration to the following introspection settings:
```yaml
introspection:
  url: http://localhost:8000/graphql/
  metadataFile: ./metadata.json

  queryDocumentedDefault: false
  mutationDocumentedDefault: false
  typeDocumentedDefault: false
  fieldDocumentedDefault: true
  argDocumentedDefault: true
  hideFieldsWithUndocumentedReturnType: false

```

This allows me to see everything like in the example on the right screenshot, but now I am looking at undocumented fields in the metadata file for types.
