### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by kev-ngo** [anvilco/spectaql#17]
## Issue
- I am trying to create GraphQL documentation from my schema file using `npx spectaql schema.txt`
- When I try it, I'm receiving the following error message:
![1](https://user-images.githubusercontent.com/69411313/115941580-c4c21e00-a45a-11eb-896c-f8f3059ec893.png)

## Attachments
Here's the schema file that I'm trying to create docs from:

[schema.txt](https://github.com/anvilco/spectaql/files/6368734/schema.txt)

**Comment by newhouse** [comment]
Hello @kev-ngo and thanks for using SpectaQL!

The first issue I see is that your command should point to a **_yaml config_** and not a **_schema_**. Inside your config, you can put a path to your schema.

Something like this (lifted from [examples/config.yml](https://github.com/anvilco/spectaql/blob/main/examples/config.yml)) should work:
```yaml
introspection:
  schemaFile: ./schema.txt

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
```

After fixing that, I am seeing some errors in processing your schema that will need to be addressed as well:
```json
[{"message":"The type of Query.getData(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":33,"column":17}]},{"message":"The type of Mutation.setData(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":46,"column":17}]},{"message":"The type of Mutation.deployContract(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":50,"column":17}]},{"message":"The type of Ethereum_Query.callView(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":65,"column":17}]},{"message":"The type of Ethereum_Mutation.sendTransaction(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":78,"column":17}]},{"message":"The type of Ethereum_Mutation.deployContract(connection:) must be Input Type but got: Ethereum_Connection.","locations":[{"line":85,"column":17}]}]
```

I'm not familiar with a lot that's going on in that schema, so I cannot really help you further on that at the moment.

I hope this helps keep you moving forward!

**Comment by kev-ngo** [comment]
Thank you!

I'm receiving this error when I try the steps you mentioned:

```bash
/home/kevin/.npm/_npx/30d8ff16066afd73/node_modules/graphql-2-json-schema/dist/lib/fromIntrospectionQuery.js:9
    const { queryType, mutationType } = introspection.__schema;
            ^

TypeError: Cannot destructure property 'queryType' of 'introspection.__schema' as it is undefined.
```

Do you know what this issue is?

### Steps to reproduce:
1) **Create a `config.yml` file and paste the following in it:**

```yml
# config.yml

introspection:
  schemaFile: ./schema.txt

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
```
2) **run `npx spectaql config.yml`**
