### ISSUE TITLE
Spectaql does not generate interfaces types as before

### ISSUE THREAD

**Issue by Matovidlo** [anvilco/spectaql#379]
I am currently using version 1.2.1 and the interfaces are not generated. Back in version 0.9.2 it is wroking correctly. Can you please fix it as before? The documentation then have not working links to the interfaces and people complain about not working links. Either remove it from docs or fix the links and generation of interfaces. Thank you in advance

**Comment by newhouse** [comment]
@Matovidlo Can you please provide a minimal set of config and SDL to reproduce for me?

**Comment by mengledowl** [comment]
We are seeing this issue as well. Pre-1.x the interface we have was included in the documentation, but after upgrading it is no longer there.

Super simple reproduction:

schema.gql:
```graphql
interface MyInterface {
  message: String!
}

type MyType implements MyInterface {
  message: String!
}

type Query {
  myQuery: MyType!
}
```

spectaql.yml
```yml
introspection:
  schemaFile: ./schema.gql

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
```
