### ISSUE TITLE
Contact and license information

### ISSUE THREAD

**Issue by raoul-thill** [anvilco/spectaql#42]
I've used the same information as in the example provided, but the license and contact information are not properly rendered. 

```yaml
info:
  description: Your description here
  version: 1.0.0
  title: Your Welcome title here
  termsOfService: 'https://yoursite.com/terms'
  contact:
    name: YourSite Support
    email: support@yoursite.com
    url: https://yoursite.com/support
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
```

The outcome of this is that the only value shown is Contact: support@yoursite.com, no name or URL for the contact and no license information at all.
