### ISSUE TITLE
Issues using with `"type": "module"` and custom theme

### ISSUE THREAD

**Issue by matoni109** [anvilco/spectaql#543]
Hi Team,

```
  "type": "module",
  "engines": {
    "node": "18.4.0",
    "yarn": "^1.22.19"
  },
  "scripts": {
    "schema:doc": "rm -rf ./build/graphqldoc && yarn spectaql spectaql-config.yml -t ./build/graphqldoc"
  },
```

```
spectaql:
  logoFile: public/images/submarine-dark-clear.png
  faviconFile: public/images/favicon.ico
  themeDir: public/themes/my-partial-theme/
```

First up thanks for the library, it's really solving a use case for us here.

I don't know if I'm missing something, but I'm trying to use the above setup and initiating with `yarn schema:doc` 

* i'm using the `my-partial-theme` out of the `node_modules` folder.
* for context the rest of the repo is ES6, with non commonJS packages

Getting below:
* any help would be super :) 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module from node_modules/spectaql/dist/spectaql/index.js not supported.
```
![image](https://user-images.githubusercontent.com/68096885/198496242-eb5a23d1-5bed-4aaa-b4ca-272c72ab2a50.png)
