### ISSUE TITLE
[solved]: `Can output JS and/or CSS "in line" in your HTML file, rather than as separate files.`

### ISSUE THREAD

**Issue by matoni109** [anvilco/spectaql#563]
Hi @newhouse,

*UPDATE:*
Ok figured it out using below:
```"scripts": {
    "esbuild": "node esbuild.config.js --minify",
    "esbuild-dev": "node esbuild.config.js --watch",
    "schema:doc": "rm -rf ./src/spectaql && yarn spectaql spectaql-config.yml --one-file --embeddable -t ./src/spectaql"
  },
```
Just trying to figure out how to do:
* **Can output JS and/or CSS "in line" in your HTML file, rather than as separate files.**
```yml
spectaql:
  logoFile: public/images/submarine-dark-clear.png
  faviconFile: public/images/favicon.ico
  themeDir: public/themes/platform-beta
  embeddable: true
```

I'm using below in `/views/embedded.hbs`

```hbs
{{! Renders the HTML page content without the <body/> tag }}
{{>layout/links-scripts}}
<div id="spectaql">
  {{>layout/page}}
</div>
```
