### ISSUE TITLE
Union types appear to be missing

### ISSUE THREAD

**Issue by stephen-opal** [anvilco/spectaql#62]
Hi there, thanks for the great library! Right now, all of my operations and types are generating, but for some reason, my union types aren't. Is this known / expected? This is my config basically:

```
introspection:
  url: http://localhost:3000/query
  hideQueriesWithUndocumentedReturnType: false
  hideMutationsWithUndocumentedReturnType: false
```

with generation command:

```
npx spectaql -JCe configs/specta-config.yaml
```

Example GraphQL spec:

```
input DeleteUserInput {
  id: UserId!
}

union DeleteUserOutput =
    DeleteUserResult
  | UserNotFoundError

type DeleteUserResult {
  user: User!
}

type Mutation {
  deleteUser(input: DeleteUserInput!): DeleteUserOutput!
}
```

Let me know if I can provide additional info. Thank you!
