### ISSUE TITLE
Metdata for "enumValues" not working

### ISSUE THREAD

**Issue by glinskyc** [anvilco/spectaql#704]
Despite trying combinations of settings for `enumsDocumentedDefault` and `enumDocumentedDefault`, nothing seems to allow the metadata in `"enumValues"` to be used.  

For example, your example `metadata.json` includes the following, but the `EMPIRE` value still gets documented.  In my testing, vice versa is also true, i.e. `"documented": true` has no effect when wanting to document only certain values of an enum, while hiding all others (an additional config variable may be appropriate to account for that use case?).

```
"ENUM": {
    "EpisodeEnum": {
      "enumValues": {
        "EMPIRE": {
          "documentation": { "undocumented": true }
        }
      }
    }
  },
```

**Comment by glinskyc** [comment]
Implementing these variables could help address the use case of documented / undocumented for individual enum values.

```yaml
  # Whether to document an individual Enum Value, in the absence of a metadata directive
  # Default: true
  enumValueDocumentedDefault: true
  # Hide any enumValues of undocumented enums so as not to reference something that seemingly does not exist.
  # Default: true
  hideEnumValuesOfUndocumentedType: true
```
