### ISSUE TITLE
Headers that differ per server?

### ISSUE THREAD

**Issue by zippocage** [anvilco/spectaql#840]
In our spectaql config.yml file, we have two servers (test and staging) that differ by URL. They also require different Authorization bearer token.

## Issue
Only headers for the first server is shown in the generated documentation (while both server URLs are listed). Is this intended or is this a bug?

## Details
If I have the following in the server section of the config.yml:
```
servers:

  - url: https://staging.example.org/api/
    description: Staging
    headers:
      - name: Authorization
        example: Bearer <STAGING_TOKEN>
        comment: This token must be provided to access the staging backend and API

  - url: https://test.example.org/api/
    description: Test
    headers:
      - name: Authorization
        example: Bearer <TEST_TOKEN>
        comment: This token must be provided to access the test backend and API
```

Then the generated documentation will render it like this:
![Screenshot 2023-06-16 at 14 31 00](https://github.com/anvilco/spectaql/assets/2931950/8c006a31-46bb-4968-ba2e-8cd4ed07669d)
